### ISSUE TITLE
Gives a module error

### ISSUE THREAD

**Issue by malikozturkk** [BuilderIO/hydration-overlay#20]
It didn't work with both Webpack and plain config.
**next.config.js**
webpack: (config, options) => {
    config = withHydrationOverlayWebpack({
      appRootSelector: "#__next",
      isMainAppEntryPoint: (entryPointName) =>
        !options.isServer &&
        (entryPointName === "pages/_app" || entryPointName === "main-app"),
    })(config);
    return config;
  },

**_app.tsx**
<HydrationOverlay>
    <ThemeProvider theme={theme}>
         <Page {...pageProps} />
    </ThemeProvider>
</HydrationOverlay>

![Screenshot 2023-12-21 at 11 16 28](https://github.com/BuilderIO/hydration-overlay/assets/94051804/87c841d3-3226-4163-8154-4dfbfd2484d4)

**Comment by saadshahd** [comment]
Fixed by adding `@builder.io/react-hydration-overlay` to next.config transpilePackages
```
transpilePackages: ['@builder.io/react-hydration-overlay'],
```

**Comment by BenjaminLesne** [comment]
@saadshahd nice! it got rid of the server error.

But I don't have the HTML diff showing up still.
Am I the only one?

**Comment by malikozturkk** [comment]
> Fixed by adding `@builder.io/react-hydration-overlay` to next.config transpilePackages
> 
> ```
> transpilePackages: ['@builder.io/react-hydration-overlay'],
> ```

Thanks, I'm trying

**Comment by malikozturkk** [comment]
> Fixed by adding `@builder.io/react-hydration-overlay` to next.config transpilePackages
> 
> ```
> transpilePackages: ['@builder.io/react-hydration-overlay'],
> ```

Thanks!!

it worked
