### ISSUE TITLE
Next 12 issue

### ISSUE THREAD

**Issue by zibra** [BuilderIO/hydration-overlay#23]
Is this tool compatible with Next.js 12?

I'm getting such error:
<img width="974" alt="image" src="https://github.com/BuilderIO/hydration-overlay/assets/4493100/d15f47a4-e2c5-4c4d-ad57-4733b60c05e3">

**Comment by BenjaminLesne** [comment]
@zibra see [this fix](https://github.com/BuilderIO/hydration-overlay/issues/20#issuecomment-1866116493)

**Comment by zibra** [comment]
So it looks like it's not possible in Next.js 12:
<img width="491" alt="image" src="https://github.com/BuilderIO/hydration-overlay/assets/4493100/19e021a0-da45-43e2-8668-3a3d32206897">

**Comment by samijaber** [comment]
Should be fixed in https://github.com/BuilderIO/hydration-overlay/releases/tag/%40builder.io%2Freact-hydration-overlay%400.0.7
