### ISSUE TITLE
Doesn't work in next.js 14.1.0 application

### ISSUE THREAD

**Issue by dogfrogfog** [BuilderIO/hydration-overlay#42]
I followed the guide step by step, but the overlay doesn't work.

Am i missing something?

setup
![Screenshot 2024-01-31 at 07 44 48](https://github.com/BuilderIO/hydration-overlay/assets/47758224/f3481cd2-e1bc-4acc-bcd2-7eec2952e7ff)

result
![Screenshot 2024-01-31 at 07 46 04](https://github.com/BuilderIO/hydration-overlay/assets/47758224/f1e38b8a-c461-49b6-9e75-a76947a51b15)

**Comment by samijaber** [comment]
You might need to update the `appRootSelector` to `body` or something else. Nextjs applications are initialized with a `<main>` element, which is why we use that as a default, but it looks like you removed yours from your app.

**Comment by dogfrogfog** [comment]
yeah you are right, thanks! figured this out 🫂
